package com.mowitnow.automaticlawnmower;

import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world. LawnMower";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
