package com.mowitnow.automaticlawnmower;
import static org.junit.Assert.assertNotNull;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.mowitnow.automaticlawnmower.Instruction.InstructionType;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        
        Set<InstructionType> instructions = Arrays.stream("AADAADADDA".split(""))
        	.map(c -> Instruction.InstructionType.valueOf(c))
        	.collect(Collectors.toSet());
    }
}
