package com.mowitnow.automaticlawnmower;

import static org.junit.Assert.*;

import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {
	

	
}
